name: Stale Issues and PRs

on:
  schedule:
    # Run every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Mark Stale Issues and PRs
    runs-on: ubuntu-latest

    steps:
      - name: Stale Issues and Pull Requests
        uses: actions/stale@v9
        with:
          # Stale issues configuration
          days-before-issue-stale: 60
          days-before-issue-close: 30
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement,help wanted,good first issue'
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed in 30 days if no further activity occurs.

            If this issue is still relevant, please:
            - Comment to keep it open
            - Add more information
            - Submit a pull request to fix it

            Thank you for your contributions!
          close-issue-message: |
            This issue was automatically closed because it has been stale for 30 days with no activity.

            If you believe this is still relevant, please reopen the issue with updated information.
          close-issue-reason: 'not_planned'

          # Stale PRs configuration
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,in progress,wip'
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 14 days if no further activity occurs.

            If you're still working on this:
            - Push new commits
            - Comment to keep it open
            - Request a review

            Thank you for your contribution!
          close-pr-message: |
            This pull request was automatically closed because it has been stale for 14 days with no activity.

            If you'd like to continue this work, please reopen the PR and push new commits.

          # General configuration
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true
          enable-statistics: true

  stale-reminder:
    name: Remind on Stale PRs
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Check for stale PRs needing attention
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'asc',
              per_page: 100
            });

            const now = new Date();
            const fourteenDaysAgo = new Date(now - 14 * 24 * 60 * 60 * 1000);

            const stalePRs = prs.filter(pr => {
              const updatedAt = new Date(pr.updated_at);
              return updatedAt < fourteenDaysAgo && !pr.draft;
            });

            if (stalePRs.length > 0) {
              console.log(`Found ${stalePRs.length} stale PRs`);

              // Create an issue to track stale PRs (optional)
              const prList = stalePRs.map(pr => `- #${pr.number}: ${pr.title}`).join('\n');

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Weekly Report: ${stalePRs.length} Stale Pull Requests`,
                body: `## Stale Pull Requests Needing Attention

            The following pull requests haven't been updated in over 14 days:

            ${prList}

            Please review these PRs and either:
            - Merge them if they're ready
            - Request changes if needed
            - Close them if they're no longer relevant

            This issue was automatically generated.`,
                labels: ['maintenance', 'automated']
              });
            }
